openapi: 3.0.0
info:
  title: SINO
  version: 1.0.0
  description: "의미있는 신호(SIGNAL)는 남기고, 불필요한 잡음(NOISE)은 줄이자"

servers:
  - description: "로컬 서버"
    url: http://localhost:3000/docs
  - description: "배포 서버"
    url: http://3.34.200.244:3000/docs

paths:
  paths:
  /api/auth/signup:
    post:
      summary: 회원가입
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  description: 닉네임 (unique)
              required:
                - nickname
      responses:
        "200":
          description: 회원가입 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
        "409":
          description: 이미 존재하는 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  statusCode:
                    type: integer
                  message:
                    type: string
        "500":
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  statusCode:
                    type: integer
                  message:
                    type: string
